version: '3.8'

services:
  verifai-api:
    build: .
    container_name: verifai_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - verifai_data:/app/data
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:///./verifai.db
      - UPLOAD_FOLDER_PATH=./uploads
      - MONGO_URI=mongodb+srv://as8304_db_user:p3wrcrwiWoAY4Rmd@verifai-cluster.enogee0.mongodb.net/?retryWrites=true&w=majority&appName=VerifAI-CLUSTER
      - MONGO_DB_NAME=verifai
    restart: always

volumes:
  verifai_data:
